### ISSUE TITLE
Websockets missing from Blueprints

### ISSUE THREAD

**Issue by pinguluk** [narknon/PhoenixUProj#11]
So I've downloaded a dump of the objects from the game
[HogwartsLegacy.zip](https://github.com/narknon/PhoenixUProj/files/10975667/HogwartsLegacy.zip)

and I see that the Websockets can't be found in the Blueprints
![image](https://user-images.githubusercontent.com/16257821/225195522-eea2ff7c-1981-456d-8b15-fd71f9fa3843.png)

![image](https://user-images.githubusercontent.com/16257821/225195505-8938ae61-e107-44ce-9b44-1b5efacb836e.png)
![image](https://user-images.githubusercontent.com/16257821/225196064-4ea62f13-8f3f-48fa-9b72-e7d302660576.png)

I'm am missing something or they need to be referenced/included in the project?

**Comment by narknon** [comment]
What exactly are you expecting to see there? Are there any reflected bpable ufunctions in that dump?

**Comment by pinguluk** [comment]
> bpable

Not sure what do you mean by reflected bpable ufunctions, but I've just found references of the websockets being used, in the objects and the scripts from that dump.
I suspect that they are using the them in the main screen menu (and settings) where you can [link your Hogwarts Legacy Fan Account](https://www.hogwartslegacy.com/en-us/link-account) 

![image](https://user-images.githubusercontent.com/16257821/225965183-6666dc12-e600-48c1-8d6e-8a99ef5d6551.png)

![image](https://user-images.githubusercontent.com/16257821/225965206-de630c88-ae9f-4db6-b7a7-5b0053478278.png)


and I was wondering if I could use them as well, in the PhoenixUProj, but couldn't find the websockets references.

**Comment by narknon** [comment]
Well, on one hand Websockets is indeed not activated in the uproject.  On the other hand, it doesn't do what you think and wouldn't show up there anyway.

**Comment by narknon** [comment]
Actually, websockets is active.
