### ISSUE TITLE
uproject not launching after generating .sln

### ISSUE THREAD

**Issue by ghost** [narknon/PhoenixUProj#12]
After trying both methods in the README.md, the project will not open.

During the step for setup.bat at https://github.com/narknon/PhoenixUProj#engine, the screenshot shown is different from what is actually shown, its not explained in the guide to say "y" or "n":
![Screenshot 2023-03-27 163938](https://user-images.githubusercontent.com/127917788/228092878-f99bf6f4-3585-4e07-a351-ae5013709ee9.png)

Upon finishing the rest of the steps, and launching the project file, a window shows up:
![Screenshot 2023-03-27 165657](https://user-images.githubusercontent.com/127917788/228092960-8b1c0882-d03f-4eb9-af38-f11dad0394d8.png)
Selecting Yes tries to build things but then says you need to build them in the IDE.
Selecting No does nothing and the project does not launch.

**Comment by AzurieWolf** [comment]
I managed to fix this.

You have to rebuild a few things with your IDE.

1). Open phoenix.sln inside of the PhoenixUProj folder.
(When it opens, you'll likely see this message. Just press Continue)
![Target_Framework](https://user-images.githubusercontent.com/25701444/228689293-0f40c729-c82b-44e4-90f0-649663ff2697.png)
2). Navigate to the Solution Explorer on the right.
3). Right click on phoenix, just below Games.
![2023-03-28_19-14-26](https://user-images.githubusercontent.com/25701444/228686721-8a3d1c60-ce40-471c-bf00-6b050a063400.png)
Note: this will take a while as it's rebuilding a lot of things.
4). after that finishes, search for "AutomationTool" and rebuild that as well.
![2023-03-29_20-01-56](https://user-images.githubusercontent.com/25701444/228687219-f32a6b9f-fea0-46ed-88f4-aaf34a47471f.png)
5). Now go to your Custom Engine folder and open UE4.sln in Visual Studio (if it doesn't exist then double click the GenerateProjectFiles.bat, after that finishes it should have created the UE4.sln file).
6). Again, in the Solution Explorer on the right, search for "AutomationTool" and rebuild that as well.

That should fix it. if you cannot build the project then you might have to rebuild the MobileDeviceInterface as well like i did.

To do that, inside of your Custom Engine folder, navigate to Engine\Source\Programs\IOS\MobileDeviceInterface and open MobileDeviceInterface.csproj in visual studio and in the Solution Explorer, right-click on MobileDeviceInterface and rebuild.
![2023-03-29_20-12-09](https://user-images.githubusercontent.com/25701444/228688420-0c2dd765-e5fd-4864-b367-9b91921236bb.png)


That should hopefully fix the issue for you. :)

**Comment by narknon** [comment]
Yeah, I'm out of town but somehow the psk plugin didn't upload everything required.  If you don't want to rebuild you can just disabled it in the uproject file.

**Comment by ghost** [comment]
Disabling in the uproject did the trick. Didnt wanna start recompiling things if I didn't need to, thanks for the help!
