### ISSUE TITLE
Uninstall instructions or support

### ISSUE THREAD

**Issue by Hoax2** [narknon/PhoenixUProj#13]
I was able to follow the instructions for installing the Prebuilt uProject and Engine for Hogwarts legacy perfectly (thank you for that). I made a few mods, but now I need to uninstall it to make room on my HDD.

-  I installed it via the `Setup.bat` but im not sure what I have to do to uninstall it?
-  Also there are UE options the in windows context menu now, do i need to do anything special to remove them cleanly?
- im cautious to just delete the folder and leave a bunch of broken registries behind 😞 

Edit. Also happy to help update the instructions once i know the appropriate process

**Comment by narknon** [comment]
For anyone seeing this later.. Just delete the files.
