### ISSUE TITLE
Unreal Editor - AutomationTool Error when cooking pak

### ISSUE THREAD

**Issue by sh0t4r0** [narknon/PhoenixUProj#6]
Hi, im trying to do a simple texture replacement and export a .pak as result (i could achieve this using the Default UE). 

This will be used to further research DA_GAs but since it is needed to use Custom UE im having the following error when trying to cook the file.

![image](https://user-images.githubusercontent.com/32794764/221014056-e4b93b97-f1aa-4a91-8664-a57b45b4a776.png)

For further troubleshoot this is my log file output from 
_UE_CEEnd427\Engine\Programs\AutomationTool\Saved\Logs\_
 
[Log.txt](https://github.com/narknon/PhoenixUProj/files/10817783/Log.txt)

I dont know if im missing something here...

**Comment by Federik1234** [comment]
same problem

**Comment by humocs** [comment]
I had the same problem. I had to rebuild the AutomationTool in Visual Studio as mentioned in other threads. Important: I had to choose **Rebuild**, Build did not work. That solved it for me.
![vs](https://user-images.githubusercontent.com/126194618/221358291-8466f416-b74e-498c-9869-19771ad0a71d.png)

**Comment by sh0t4r0** [comment]
I was using only **Build** the _AutomationTool_ before, using Rebuild solved the problem
