### ISSUE TITLE
AutomationTool exiting with ExitCode=1 (Error_Unknown)

### ISSUE THREAD

**Issue by ChristopheKASH** [narknon/PhoenixUProj#9]
I have an error with AutomationTool when I try "File" -> "Package Project" -> "Windows (x64)" (I don't have any new file I was trying to pack without modification to test everything was working fine)

[Log.txt](https://github.com/narknon/PhoenixUProj/files/10892085/Log.txt)

**Comment by narknon** [comment]
You can open the .sln in the uproject directory with visual studio, then under programs to the left find automation tool, right click and press build selected

**Comment by ChristopheKASH** [comment]
Thanks for the answer, I have build (and rebuild) but I still have the same problem:

[Log.txt](https://github.com/narknon/PhoenixUProj/files/10892387/Log.txt)

![Sans titre](https://user-images.githubusercontent.com/126481491/222975386-aa1fdf81-be33-49ab-b6e2-ded0b16fba4f.png)

![Sans titre1](https://user-images.githubusercontent.com/126481491/222975444-b2247dc9-4dab-4d20-9f65-da60a04d4e74.png)

**Comment by ChristopheKASH** [comment]
Fixed, (FYI in VS22 i have switch sdk w10 10.0.20348.0  to 10.0.19041.0)
